version: '3'

services:
  academy_gamification_database:
    image: postgres
    container_name: academy_gamification_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=academy
      - POSTGRES_PASSWORD=gcb123
      - POSTGRES_DB=academy_gamification_database
    volumes:
      - pgdata:/data/postgres
    networks:
      - gamification

  app:
    build: .
    container_name: academy_gamification
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - academy_gamification_database
    networks:
      - gamification

networks:
  gamification:
    driver: bridge

volumes:
  pgdata:
